version: "3.5"
services:
  nginx:
    image: nginx:1.22
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
